import { StyleSheet } from 'react-native';

export const signupStyles = StyleSheet.create({
    screen: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingTop: 0,
        paddingBottom: 40,
        paddingHorizontal: 20,
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        marginBottom: 30,
        textAlign: 'center',
        color: '#333',
    },
    subtitle: {
        fontSize: 14,
        color: '#9A89FF',
        marginTop: -20,
        marginBottom: 30,
        textAlign: 'center',
    },
    form: {
        width: '100%',
        alignItems: 'center',
        marginTop: 20,
    },
    input: {
        width: '100%',
        height: 50,
        backgroundColor: '#FFFFFF',
        borderRadius: 25,
        paddingHorizontal: 20,
        fontSize: 16,
        color: '#333',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    inputLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
        marginLeft: 4,
        alignSelf: 'flex-start',
    },
    button: {
        marginTop: 20,
        borderRadius: 25,
        width: '100%',
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    errorText: {
        color: '#FF6B6B',
        fontSize: 12,
        marginTop: -12,
        marginBottom: 8,
        marginLeft: 4,
        alignSelf: 'flex-start',
    },
})